[package]
name = "gtr-core"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror = "2"
nanoid = "0.4"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
serde_json = "1"
